### ISSUE TITLE
[Suggestion] Dispenser action

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#10]
Have the tempad be activated in a dispenser and open a portal to a random location from the list

**Comment by CodexAdrian** [comment]
I’m planning on creating a device that allows you to create portals with a machine of some type.

**Comment by JaisDK** [comment]
that was my first idea, I just like reusing vanilla stuff when possible

**Comment by CodexAdrian** [comment]
Normally I’d agree but I have some other things I want the device to do, namely the size of the portal that the device summons next to it and for it to stay open for a prolonged period of time, with redstone control
