### ISSUE TITLE
[Bug]: Tempad Renders Over Blocks With Blur Enabled

### ISSUE THREAD

**Issue by PolyframeX** [terrarium-earth/Tempad#100]
### Bug Description

When Using Blur Mode, The Tempad Will Render Ontop Of Everything. Including Blocks. 
![image](https://github.com/terrarium-earth/Tempad/assets/80133652/45260793-9002-475d-a541-ddfc6880ec49)

### How to Reproduce?

1. Enable Blur Mode
2. Create A Portal
3. Go Behind A Wall

### Expected Behavior

Tempad Should Not Be Visible

### Version

2.3.3

### Mod Loader Version

0.15.7

### Mod Loader

Fabric

### Logs or additional context

Mod List: https://pastebin.com/XBCUTPAT

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is a known issue, that’s why this mode is disabled by default for the moment
