### ISSUE TITLE
[Bug]: Tempad not visible with shaders

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Tempad#101]
### Bug Description

When you have shaders you can't see the portal. It's still there but you can't see it.

### How to Reproduce?

1. Use shaders
2. Use the tempad --> Not visible
3. Disable shaders
4. Use the tempad --> Visible

### Version

2.3.3

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
known issue

**Comment by Geccpls** [comment]
Could we get a config for less fancy rendering that would be compatible with shaders..? I don't need the full visual, but being able to see a static block would be really nice.

**Comment by CodexAdrian** [comment]
You can use [this](https://www.curseforge.com/minecraft/mc-mods/tempad-with-shaders) mod to fix this issue

**Comment by Geccpls** [comment]
Unfortunately that only works for Forge, not Fabric.
