### ISSUE TITLE
[Feature Request]: Dimension Blacklist expansion

### ISSUE THREAD

**Issue by Rythian2277** [terrarium-earth/Tempad#103]
### Mod Version

N/A

### Mod Loader Version

N/A

### Mod Loader

NeoForge, Forge

### Additional context

With the introduction of the Dimension Blacklist feature, I think itd be great to allow this to be set per Tempad type (Original, HWR), letting users configure the blacklisted dimensions on a version basis which would then be able to grant the HWR version of the tempad access to additional dimensions which the original could not.

(I am aware this feature will not be backported to my current version but would be useful for others)

**Comment by CodexAdrian** [comment]
Im changing the way the tempads work, so 2 tags wouldnt make sense for this anymore
