### ISSUE TITLE
[Feature Request]: Sort/Rearrange locations in list

### ISSUE THREAD

**Issue by drysdan** [terrarium-earth/Tempad#105]
### Is your feature request related to a problem?

The list of destinations can rapidly get quite full, and while the search feature helps, it would be nice to be able to rearrange them so the most frequently or most recently used ones were at the top for quicker access

### Mod Version

2.3.3

### Mod Loader Version

47.2.20

### Mod Loader

Forge

**Comment by cstalker** [comment]
yes please yes. or how about unique temp pads that dont use the waystone info,

**Comment by CodexAdrian** [comment]
in 1.21 you will be able to collapse entries and disable the rendering of entire entries. This should help you manage tempads with a ton of different locations
