### ISSUE TITLE
[Bug]: Location Card

### ISSUE THREAD

**Issue by Vitokhv** [terrarium-earth/Tempad#106]
### Bug Description

Thank you for this mod, it is very nice and convenient (and in the style of the series), but there is a problem that does not allow you to create working cards to share them with players

There is a problem - when the location card contains coordinates, it can no longer be renamed, the name will be the old one, if it was called "Location Card" then renaming it on the anvil, it will still be in the tempad list under the name "Location Card", only the name of the card will change, but not the name location inside the tempad

We also very often accidentally click on the “delete” button instead of “teleport”, and then it is completely disappointing to lose the coordinates, which are very difficult to find again later (the delete button is located very close to the “teleport” button) it is advisable to swap it, or move it a little further, Even selecting yes/no when deleting will help)

![2024-04-03_21 00 44](https://github.com/terrarium-earth/Tempad/assets/23352451/b5f9ffca-52f5-4e46-8cb0-7e47d24781c5)

### How to Reproduce?

Not a working method
1. Pick up a “blank” map without coordinates
2. Right click for the first time mouse (notification received - Set location: Location Card)
3. Rename on anvil (Name 1)
4. Right click a second time mouse (notification received - Added location: Location Card)
5. Open the tempad and see the error in the location name (Location Card), the card itself is under the name "Name 1"

Almost working method
1. Pick up a “blank” map without coordinates
2. Rename on anvil (Name 2)
3. Right click for the first time mouse (notification received - Set location: Name 2)
4. Right click a second time mouse (notification received - Added location: Name 2)
--->
5. Remove from the list tempad "Name 2"
6. Rename on anvil (Name 2 to Name 3)
7. Right click mouse (notification received - Added location: Name 2)
8. Open the tempad and see the error in the location name (Name 2), the card itself is under the name "Name 3"

### Expected Behavior

The anvil should also rename the name of the location in the tempad list

### Version

2.3.7

### Mod Loader Version

1.20.4 - 20.4.216

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Vitokhv** [comment]
Not enough yet in tempad - button "renaming location"

**Comment by CodexAdrian** [comment]
These issues are now fixed in the new UI
