### ISSUE TITLE
Tempad 1.20.1-ver. 2.3.3 switching between Timer and Energy within the Config file.

### ISSUE THREAD

**Issue by Tahlavos17** [terrarium-earth/Tempad#109]
### Bug Description

I recently tried to switch from a Timer based source of fuel to that of a RF Energy for a source of fuel since I've got a way to make RF Energy setup within a modpack that I'm working on, but it still uses the Timer Fuel Source instead of the Energy based Fuel Source. My Energy providing source is Powah 5.0.5 with the wireless energy transmitter being that of Flux Network 7.2.0.14. What seems to be the problem on that front??

### How to Reproduce?

I've gone through and put energy where it is required, but it still uses the timer cooldown.

### Expected Behavior

I was expecting the config change to be swift to use the energy that I've got stored up to recharge the Tempad but nothing has changed from what I've experienced with the mod itself.

### Version

Tempad 1.20.1-2.3.3

### Mod Loader Version

1.20.1-47.1.101

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by MonaMoonlight** [comment]
I've been having a similar issue switching between Forge Energy and XP.

Best I can tell, the wiki documentation for changing the config is outdated.

Setting `"timedoorFuelType": "tempad:energy",` does make it use energy, as per the config, so that should hopefully work for you, but I've tried "tempad:exp_points" and several other variations on XP, and not managed to find the right one to switch to experience points.

**Comment by CodexAdrian** [comment]
This one seems to be user error, please check https://tempad.wiki to see all the valid types and how they work
