### ISSUE TITLE
[Feature Request]: Config for disallowing entities to passthrough the portal

### ISSUE THREAD

**Issue by Xplodin** [terrarium-earth/Tempad#110]
### Is your feature request related to a problem?

Ender dragon can be tp'd to overworld

### Solution(s)

a blacklist for specific or all mobs that arent the player

### Describe alternatives you've considered

none

### Mod Version

2.3.3

### Mod Loader Version

1.20.1-47.2.20

### Mod Loader

NeoForge, Forge

### Additional context

I dont know how else this can be dealt with

**Comment by CodexAdrian** [comment]
This is already a feature `tempad:tempad_entity_blacklist`

**Comment by Xplodin** [comment]
> This is already a feature `tempad:tempad_entity_blacklist`

sorry to be a bother, how would I add an entity to this tag?

**Comment by CodexAdrian** [comment]
You do it the same way you add an entity to any other tag, with a datapack

**Comment by Xplodin** [comment]
got it via kubejs, ty
