### ISSUE TITLE
[Bug]: Adding enchantments to the tempad removes colour

### ISSUE THREAD

**Issue by ShadowFox88** [terrarium-earth/Tempad#111]
### Bug Description

Adding an enchantment to the He Who Remains Tempad removes the orange colour, as the colour code symbol is wiped. The name becomes 6Tempad in italics, rather than staying the same.

### How to Reproduce?

1. Get a He Who Remains Tempad
2. Find an enchant that's applicable to it (I'm using soulbound from the You're In Grave Danger mod)
3. Add the enchant in an anvil
4. Observe the changed name.

### Expected Behavior

A normal coloured item with enchants should have the name stay the same as shown (I'm using the Gravichestplate from Modern Industrialisation)
![image](https://github.com/terrarium-earth/Tempad/assets/66386770/03c54691-44f4-459f-a0e3-746bab8a8249)
The tempad does not have the same property
![image](https://github.com/terrarium-earth/Tempad/assets/66386770/048a801a-26e4-422c-955d-3486ad6799c4)

### Version

2.33

### Mod Loader Version

1.20.1 - 0.15.10

### Mod Loader

Fabric

### Logs or additional context

I think this is caused by the fact that the name for the Tempad is "§6Tempad", rather than being set to orange through some other method, but I don't know enough about how to fix such an issue.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Oh interesting, never thought about soulbound. As a stopgap until i fix it, you can fix the lang for the name as it has the color code included in it. You can change the lang with a resource pack

**Comment by DeltaAxis-9** [comment]
i am also currently have this issue while playing the "ATM9" pack and I cannot change the color back. Would be  W id the devs could fix

**Comment by CodexAdrian** [comment]
Fixed in 1.21
