### ISSUE TITLE
[Bug]: Tempad crashes client on game loading. (Development Environment)

### ISSUE THREAD

**Issue by YoItSoul** [terrarium-earth/Tempad#113]
### Bug Description

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tempad-common.mixins.json:LevelRendererMixin] from phase [DEFAULT] in config [tempad-common.mixins.json] FAILED during APPLY
```

In a custom mod environment, during Initialization, Tempad causes a crash for the client.
This environment is a custom mod that implements spawning tempads around/in structure by checking for their presence, and respawning them if they don't already exist.

I have already tried disabling (my) mod items that interact with Tempad to isolate the issue, upon removing tempad - the client can load.

### How to Reproduce?

Run "runClient".

### Expected Behavior

Client crash log.

### Version

2.3.3

### Mod Loader Version

1.20.1 - 43.7.0

### Mod Loader

Forge

### Logs or additional context

https://hastebin.com/share/quharaqiju.yaml

```
minecraft "net.minecraftforge:forge:1.20.1-47.3.0"

    implementation fg.deobf("com.teamresourceful.resourcefulconfig:resourcefulconfig-forge-1.20.1:2.1.2")
    implementation fg.deobf("com.teamresourceful.resourcefullib:resourcefullib-forge-1.20.1:2.1.25")
    implementation fg.deobf("curse.maven:tempad-514923:5008918")
```

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Tempad is also available on a maven, use:

`implementation fg.deobf("me.codexadrian.tempad:tempad-forge-1.20.1:2.3.4")`

Tempad uses mixins in 1.20.1, so you also need to follow this if you're trying to depend on it from a forge environment
<img width="827" alt="image" src="https://github.com/user-attachments/assets/22f9f839-fd56-4d7a-aef6-09800803fada">
