### ISSUE TITLE
[Feature Request]: Remove Tempad Spawn Pad in End 1.19.2

### ISSUE THREAD

**Issue by Pnegiun** [terrarium-earth/Tempad#116]
### Is your feature request related to a problem?

When you save a location in the end and then teleport to it, it creates an obsidian spawn pad similar to the one when you enter through an end portal. The spawn pad replaces existing blocks. In later versions of the mod, this is removed, but there is no 1.19.2 version without it.

### Solution(s)

Publish another 1.19.2 update that has the spawn platform removed. 

### Mod Version

1.4.5

### Mod Loader Version

1.19.2 - 43.2.14

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
1.19.2 is no longer supported, please update to 1.20.1 or later
