### ISSUE TITLE
[Bug]: can't remove saved location

### ISSUE THREAD

**Issue by howtfisallnamestaken** [terrarium-earth/Tempad#120]
### Bug Description

![image_2024-08-18_170437929](https://github.com/user-attachments/assets/f9f9996d-95ca-499f-b99e-a871517fd9bc)
i cant click remove

### How to Reproduce?

1. create waypoint in xeros world map 2. leave and save world 3. try to remove the waypoint created in the tempad

### Expected Behavior

i expected that when i removed the waypoint in the tempad or xeros world map it would remove the option to create a gate

### Version

2.3.4

### Mod Loader Version

1.20.1 minecraft 0.16.0 fabric loader

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is intended. if you want to delete locations from xaeros, you have to delete it through Xaeros itself.

**Comment by howtfisallnamestaken** [comment]
You don't understand i could delete the location on Xaeros but it would stay on the Tempad plus a cant add locations to the Tempad from Xearos anymore

**Comment by CodexAdrian** [comment]
The Tempad API is designed where it’s the implementer of the location provider to handle this stuff. Tempad does not handle Xaeros support, so you’ll have to report this issue to the dev who added compat between Xaeros and Tempad

**Comment by howtfisallnamestaken** [comment]
well who added compatibility?

**Comment by CodexAdrian** [comment]
Idk, wasn’t me tho
