### ISSUE TITLE
Cooldown time broken in Multiplayer

### ISSUE THREAD

**Issue by Sebas-Re** [terrarium-earth/Tempad#14]
In singleplayer works as expected but, for some reason, the cooldown time breaks in multiplayer, and after those initial 3 minutes, instead of showing "fully charged" the cooldown time changes to 1hr.

Tempad status changes to "fully charged" after that hour

![image](https://user-images.githubusercontent.com/32151264/166582152-96ce0c5e-f998-4e91-98df-0c3a70d8919a.png)
![image](https://user-images.githubusercontent.com/32151264/166583585-3a3ed33c-dd29-4e91-a750-31fa0888f3e7.png)

**Comment by ogpw** [comment]
Same for me. Using a config time of 3s worked the first time, time after that was 59:59. Modded Fabric 1.18.2 Server.

Edit:
Line 53 of Common/src/main/java/me/codexadrian/tempad/network/messages/SummonTimedoorPacket.java:
"//player.getCooldowns().addCooldown(player.getItemInHand(message.hand).getItem(), 3600);".
Perhaps the code compiled and released onto Curseforge has the double slash accidentally removed and forgotten about?
(using release "fabric-1.18.2-1.1.0" btw)

**Comment by Sebas-Re** [comment]
> Same for me. Using a config time of 3s worked the first time, time after that was 59:59. Modded Fabric 1.18.2 Server.
> 
> Edit: Line 53 of Common/src/main/java/me/codexadrian/tempad/network/messages/SummonTimedoorPacket.java: "//player.getCooldowns().addCooldown(player.getItemInHand(message.hand).getItem(), 3600);". Perhaps the code compiled and released onto Curseforge has the double slash accidentally removed and forgotten about? (using release "fabric-1.18.2-1.1.0" btw)

Yeah, I just hope they release an update soon to fix this, my players are just not enjoying it that much due to this :/

**Comment by ogpw** [comment]
As it turns out:

>  This is an issue I’m aware of. This has to do with something stupid I did with how the timer works. Im hoping to get an update out to fix it. The problem lies with your computer being in a different time zone than your server. Let’s say you use the Tempad at 9 pm EST. so while the server sets the time that the cooldown will finish at 9:03 pm, your computer’s time is still only 8:03 pm because you’re in a different time zone, so it makes you wait an hour instead of just 3 minutes. I’ll try to get this fixed as soon as I can, but rest assured I know where the issue lies

The author is already aware of the issue and working on a fix. (I also tried fiddling with my server's timezone and setting it to my computer's timezone and the problem did indeed disappear - not a fix for players across multiple timezones on a single server, however).

**Comment by CodexAdrian** [comment]
Fixed
