### ISSUE TITLE
[Fabric] Unable to summon entity

### ISSUE THREAD

**Issue by Chribit** [terrarium-earth/Tempad#15]
The tempad does not create any portals.
Summoning a portal via command (/summon tempad:timedoor) returns the error "Unable to summon entity".

This is on Fabric 1.18.2.
I'm using various performance mods such as sodium and entity culling, maybe there's an incompatibility here?

**Comment by CodexAdrian** [comment]
I fixed it but the time door won't work properly unless you give it all the info it needs in the nbt
