### ISSUE TITLE
Teleport button make sound when disabled.

### ISSUE THREAD

**Issue by ThatGravyBoat** [terrarium-earth/Tempad#21]
please fix it now or bad 🙂🙂.

L + Ratio 👍

**Comment by PoolloverNathan** [comment]
...any possibility of being more specific?

**Comment by ThatGravyBoat** [comment]
The teleport button makes a sound when clicking when it's disabled.

**Comment by ThatGravyBoat** [comment]
kinda forgot that other people besides Adrian would ever think about looking into it and possibly fixing it lol

**Comment by CodexAdrian** [comment]
Gravy is bein a goofball, we're besties lol

**Comment by AlexNijjar** [comment]
no maidens

**Comment by CodexAdrian** [comment]
Fixed! it only took a year!
