### ISSUE TITLE
[FORGE] Tempad breaks MineColonies build preview

### ISSUE THREAD

**Issue by bookerthegeek** [terrarium-earth/Tempad#22]
## HEYO ##

Versions:
- Minecraft: 1.18.2
- Tempad: 1.19-1.2.5.jar
- Minecolonies: 1.18.2-1.0.737-RELEASE.jar
- Structurize: 1.18.1-1.0.401-RELEASE.jar

### The Issue ###
On an install with only Tempad & MineColonies (along with required dependencies) the preview feature when placing building with MineColonies is broken and does not show the preview in game. Disabling Tempad fixes the issue.

### P.S. ###
Thank you for reviewing my issue and I look forward to a resolution. Have a great day!

**Comment by Xenimus0** [comment]
look for the file tempad_client in your config folder, change "timedoorFancy": true to "timedoorFancy": false, after doing this I was able to fix this exact issue. This is a client side issue/fix, the server config doesn't have this setting.

**Comment by bookerthegeek** [comment]
Would it be possible for this config to automatically be changed if Structurize is detected? This will solve the issue before it can happen for people building packs without having to google-fu the answer.

Thank you for the response. :)

**Comment by CodexAdrian** [comment]
See #23 for my answer
