### ISSUE TITLE
Fancy Timedoor conflicts with Create mod rendering

### ISSUE THREAD

**Issue by Nostalgion** [terrarium-earth/Tempad#23]
many functions of create mod's rendering break heavily or fully when the fancy timedoor config setting is on, (this is default), turning it off fixes it, but this does mean less nice portals obviously.

**Comment by SammySemicolon** [comment]
It also causes issues with various mods which RenderLevelLastEvent deferr their rendering it seems, malum, eidolon, etc come to mind. 
The option for users to just turn off fancy is always there, but I feel this will bother you guys more than it's worth, RLLE deferred rendering is pretty overpresent nowadays.

**Comment by CodexAdrian** [comment]
So you guys are suggesting I make the fancy rendering turned off by default?

**Comment by CodexAdrian** [comment]
My temporary solution is that if Tempad detects an incompatible mod on first startup, it will automatically generate the config to have the fancy rendering as disabled. I think this should greatly help modpack authors
