### ISSUE TITLE
Crash on latest [1.19 Fabric]

### ISSUE THREAD

**Issue by Zainyest** [terrarium-earth/Tempad#27]
I'm using:
-Fabric 0.14.8
-Fabric API 0.57.0
-Tempad 1.4.0
-MultiMC

I just noticed that this latest version seems to crash even by itself before the minecraft initial loading screen, here's the crash report and let me know if you need any other logs:

https://pastebin.com/Qxq5ksCz

[crash-2022-07-27_14.55.52-client.txt](https://github.com/terrarium-earth/Tempad/files/9203897/crash-2022-07-27_14.55.52-client.txt)

**Comment by CodexAdrian** [comment]
Fixed
