### ISSUE TITLE
Incompatibility with mod lifts, blurry screen

### ISSUE THREAD

**Issue by BlakyHaraz** [terrarium-earth/Tempad#32]
Hi,
just find another incompatibility with the mod lifts. (https://www.curseforge.com/minecraft/mc-mods/lifts)
If u place the lift screen everything gets blurry.

After setting timedoorFancy to False, it works without shaders.
With enabeld shaders it looks not very good, but the blurry effect is gone.

**Comment by CodexAdrian** [comment]
The blurry effect is very hard to make work with other mods, so by default it turns itself off if we find a mod that breaks it. I'll add lifts to the incompatible mods list
