### ISSUE TITLE
Scrolling large location lists causes items to resort non-alphabetically

### ISSUE THREAD

**Issue by alexdelifer** [terrarium-earth/Tempad#35]
Version 1.4.1
MC: 1.18.2
Stoneblock 3 modpack
Gui scale 3 (maybe that matters)

When I open my location list with 13+ locations, it's sorted alphabetically like normal, but when I scroll my mouse wheel to see more locations, the whole list "resorts" itself to a totally different order, makes it really difficult to track down that one spot.

I had put special characters in some location's names so they'd be sorted to the top, but that's not working now.

I recreated it in another creative world to try to track it down, here's what I saw.

Freshly opened with 13 locations

![2022-12-20_05 57 24](https://user-images.githubusercontent.com/1463882/208651099-f4023551-967f-49f7-8677-4230b74188b3.png)

Scroll down 1 item

![2022-12-20_05 57 29](https://user-images.githubusercontent.com/1463882/208651133-2b9444eb-029f-4191-82b9-653b381e83ff.png)

Thanks for a cool mod!

**Comment by TMdeRuyter** [comment]
Unfortunately this still seems to be unresolved :/

**Comment by CodexAdrian** [comment]
This has been fixed in 1.20

**Comment by SijyKijy** [comment]
@CodexAdrian 
> This has been fixed in 1.20

Should we expect a fix for 1.19.2?
