### ISSUE TITLE
[Bug]: Crash during sided_setup phase

### ISSUE THREAD

**Issue by scmcgowen** [terrarium-earth/Tempad#37]
### Bug Description

Game Crashes during sided setup with mod loading error. Crash report is included

### How to Reproduce?

Start Game.

### Expected Behavior

Game starts normally

### Version

1.4.1

### Mod Loader Version

1.19.2 Forge 43.2.3

### Mod Loader

Forge

### Logs or additional context

[crash-2023-01-17_17.03.12-fml.txt](https://github.com/terrarium-earth/Tempad/files/10440635/crash-2023-01-17_17.03.12-fml.txt)

**Comment by CodexAdrian** [comment]
Fixed in latest
