### ISSUE TITLE
[Bug]: Not rendering portal with shaders and config issue,

### ISSUE THREAD

**Issue by A00826925** [terrarium-earth/Tempad#38]
### Bug Description

Currently the portal does not render with shaders on (1.19.2 latest), even with fancy portal turned off. If it should work with fancy portal off, then i think the config might not be loading correctly since i tried modifying timedoorUsageType to NONE and as a failsafe i changed timdoor_cooldown to 0 and i still need to wait 3 minutes after each use to use it again. Maybe i changed the wrong config (i used tempad.json in the config folder).

this is my modlist: https://www.curseforge.com/minecraft/modpacks/better-forever

Im using complementary shaders on medium and compatibility mode ON

### How to Reproduce?

Start game with linked mods
Enable complementary shaders (for more precision, on medium with compatibility mode ON)
Use tempad and open a portal, should be invisible

### Expected Behavior

Portal should be visible

### Version

1.19.2-1.4.3 

### Mod Loader Version

1.19.2-43.2.0 

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
The config needs to be changed on both client and server, it does not auto sync to clients.

**Comment by A00826925** [comment]
by client and server you mean in multiplayer? cause im not playing on any server right now

**Comment by CodexAdrian** [comment]
Should be fixed in latest

**Comment by A00826925** [comment]
It works now but i had to delete and regenerate the configs for the update to work, might wanna add that to the changelog, also i think timeDoorFancy might be reversed, since true works with shaders, while false doesn't (unless this is the intended functionality)
