### ISSUE TITLE
[Bug]: Invisible mobs when Rubidium is installed

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Tempad#41]
### Bug Description

![image](https://user-images.githubusercontent.com/63996164/220045176-6d91fa65-29ea-4ae5-8d8a-eb59fc82a43d.png)

### How to Reproduce?

use it with rubidium

### Expected Behavior

not have invisible mobs when a portal is active

### Version

1.4.4

### Mod Loader Version

1.19.2 43.2.2

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
This is fixed in 1.20
