### ISSUE TITLE
[Feature Request]: Teleport only on conditions

### ISSUE THREAD

**Issue by enmumne** [terrarium-earth/Tempad#42]
### Is your feature request related to a problem?

I'm still looking for a teleport-like mod that can be configured as I want.

Usually the options are about teleport costs, or the recipe of the device.

What I need instead is that it works on one condition: that the player's inventory is empty.

Basically I want teleportation as long it doesn't involve items.

### Mod Version

xx

### Mod Loader Version

1.19.2

**Comment by CodexAdrian** [comment]
Ive been considering adding a KubeJS mode for the tempad that allows you to set your own criteria and has its own trigger action.

**Comment by CodexAdrian** [comment]
When KubeJS for 1.20 is released i will likely add this feature

**Comment by TheDeviantCrafter** [comment]
KubeJS for 1.20 is out btw

**Comment by CodexAdrian** [comment]
this is now implemented
