### ISSUE TITLE
[Bug]: `minecraft:glowing` effect is not visible with this mod installed

### ISSUE THREAD

**Issue by dsf3449** [terrarium-earth/Tempad#43]
### Bug Description

The effect `minecraft:glowing` is no longer visible when this mod is installed.

### How to Reproduce?

1. Have an instance of minecraft with only forge installed

![javaw_l96OsauWkJ](https://user-images.githubusercontent.com/25350725/224451141-5ff8b7d8-12e9-428f-9153-d602fe17f98f.png)

2. Create a world
3. Write `/effect give @e minecraft:glowing 10`
4. Observe all the entities glowing

![javaw_aParr2OzFE](https://user-images.githubusercontent.com/25350725/224451184-32a27837-5f24-43e5-8c51-c99f4735188c.png)

5. Write `/effect clear @e`
6. Shut down the instance, install this mod

![javaw_VVuppS7nm2](https://user-images.githubusercontent.com/25350725/224451209-be75c15a-7686-4622-99ed-0aac4858e6aa.png)

7. Load into the world you created earlier
8.  Write `/effect give @e minecraft:glowing 10`
9. Observe that the entities do not glow this time around

![javaw_Zf7reASHTX](https://user-images.githubusercontent.com/25350725/224451232-e5a830f6-4ecb-4d46-a1e7-abd4e018b1eb.png)

### Expected Behavior

The glowing effect should function properly.

### Version

1.4.4

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

**Comment by FinityKing** [comment]
This is also happening in Minecraft 1.19.2 on forge version 43.2.6

**Comment by EvilDylan** [comment]
Changing "timedoorFancy" to false in tempad_client.json appears to have solved the issue on my end. Issue with the time door rendering?

**Comment by CodexAdrian** [comment]
Believe this has been fixed
