### ISSUE TITLE
This mod is interacting with Travel Anchors to make travel anchors render invisible [Bug]: 

### ISSUE THREAD

**Issue by Old-Man-D** [terrarium-earth/Tempad#44]
### Bug Description

While trying to track down why my travel anchors stop rendering in ATM, I did a binary search and found that this mod is some how interacting with that mod to produce the effect.  I then tested it by running an instance with just tempad, travel anchors, and Libx and the issue persists.  

https://github.com/AllTheMods/ATM-8/issues/1143

### How to Reproduce?

have all three mods installed then place a travel anchor.  Then have the teleportation rod or any tool with the teleportation enchantment.

### Version

1.4.4

### Mod Loader Version

1.19.2 43.2.6

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by superdusto** [comment]
I was able to get this to work by enabling a shader pack that came with ATM8. Without the shader pack the blocks aren't visible while holding an item with teleportation. I hope this information is useful.

**Comment by Old-Man-D** [comment]
I can confirm the same behavior.  With the shader _on_, it works as intended.

**Comment by sarpuser** [comment]
Which shader is this? Is there a name?

**Comment by Old-Man-D** [comment]
when I have the shaders turned on, I am using comp reimagined.  I did not try others.

**Comment by sarpuser** [comment]
My hardware is not powerful enough to run any of the shaders :( Guess I am stuck with guessing where to teleport

**Comment by necauqua** [comment]
@sarpuser you can set "tempadFancy" in client config (.minecraft/config/tempad_client.json) to false, it fixes it.

**Comment by Old-Man-D** [comment]
> @sarpuser you can set "tempadFancy" in client config (.minecraft/config/tempad_client.json) to false, it fixes it.

my config does not have that option.  the closest thing is "timedoorFancy", is that what you meant?

**Comment by necauqua** [comment]
yep, memory of a fish :)

**Comment by Old-Man-D** [comment]
that fixed it for me, thanks

**Comment by sarpuser** [comment]
Absolute legends. Thanks a lot.

**Comment by Mitchell5200** [comment]
Properly fixed with Tempad v1.4.5

**Comment by CodexAdrian** [comment]
This was fixed i forgot to close this
