### ISSUE TITLE
[Bug]: With TimedoorFancy set to false some fluids and chests vanish, as does the "Door"

### ISSUE THREAD

**Issue by Mitchell5200** [terrarium-earth/Tempad#45]
### Bug Description

With TimedoorFancy set to false some fluids, chests, and the Tempad "Door", vanish when the door gets opened.
First found in ATM8 while testing #44 , and confirmed in an isolated 1.19.2 instance with just JEI, JER, JEP and Tempad
Test instance modlist below
jei-1.19.2-forge-11.6.0.1013.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
tempad-forge-1.19.2-1.4.4.jar

Images Below (from test instance)
![2023-04-22_18 17 34](https://user-images.githubusercontent.com/45913837/233778328-0ab40aad-da87-42a9-beb8-c589a24e3082.png)
![2023-04-22_18 17 36](https://user-images.githubusercontent.com/45913837/233778324-13b4b1d5-8fd0-424c-a68b-3a034e470166.png)

Images from an ATM8 test world
![2023-04-22_17 04 32](https://user-images.githubusercontent.com/45913837/233778788-428d9a7d-3c1b-4d58-94f7-f7f09bc6cd25.png)
![2023-04-22_17 04 37](https://user-images.githubusercontent.com/45913837/233778780-6ac5c3d0-6172-4ef6-9818-6418e9bbdfce.png)

Additional comparison with fancy set to True
![2023-04-22_18 52 19](https://user-images.githubusercontent.com/45913837/233779906-34244ee0-37eb-4791-af91-7a0f655b82ae.png)

### How to Reproduce?

1, set timedoorFancy to false
2, get a tempad
3, open a "door"
4, where's the water gone?

### Expected Behavior

Stuff to render?

### Version

1.4.4

### Mod Loader Version

1.19.2 - 43.2.6

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Mitchell5200** [comment]
99% fixed with tempad v1.4.5. Only a minor visual issue remains with fancy set to false
![2023-06-14_17 49 18](https://github.com/terrarium-earth/Tempad/assets/45913837/c65a3614-17fb-46b6-b9aa-1e07484906a8)

**Comment by CodexAdrian** [comment]
This has been fixed, water issue is a separate and noted issue
