### ISSUE TITLE
[Feature Request]: Ability to sort locations.

### ISSUE THREAD

**Issue by SgtSnipey** [terrarium-earth/Tempad#46]
### Is your feature request related to a problem?

I have sometimes noticed the tempad randomly resorts locations.

### Solution(s)

It to not resort locations randomly and give us the ability to resort them would be amazing. By this I mean like the waystones in any order I want.

### Mod Version

1.4.4

### Mod Loader Version

43.2.8

### Mod Loader

Forge

### Additional context

Great mod everyone, I really do love it regardless of the random sorting.

**Comment by Malminas** [comment]
an alternative could be to list them alphabetically/alphanumerically; maybe symbols could be used to place things at the top or bottom? any symbols such as: ~`!@#$%^&*()-_=+\|/><?

**Comment by Malminas** [comment]
> an alternative could be to list them alphabetically/alphanumerically; maybe symbols could be used to place things at the top or bottom? any symbols such as: ~`!@#$%^&*()-_=+|/><?

Seems its supposed to list them exactly like this, but with large lists it disrupts it

**Comment by SgtSnipey** [comment]
That explains why it doesn't work for me, my list is about 3 or 4 pages.

**Comment by CodexAdrian** [comment]
this is fixed in 1.20
