### ISSUE TITLE
[Feature Request]: JourneyMap Integration

### ISSUE THREAD

**Issue by Jerry260102** [terrarium-earth/Tempad#47]
### Is your feature request related to a problem?

When creating teleport locations in tempad, still need to create waypoint in journeymap to have a visual representation of where the location is in world

### Solution(s)

When a teleport location is added to tempad a waypoint should be added in journeymap or vice versa (when waypoint is created in journeymap the location should be added to tempad)

### Mod Version

1,4,5

### Mod Loader Version

1.19.2 - 43.2.14

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
I have no plans to add journey map integration in this way
