### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by CosmosFury13** [terrarium-earth/Tempad#49]
### Bug Description

someyimes i add new mods or update mods i get this crash and message:

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "me.codexadrian.tempad.TempadClientConfig.renderBlur()" because the return value of "me.codexadrian.tempad.TempadClient.getClientConfig()" is null
[latest.log](https://github.com/terrarium-earth/Tempad/files/11984581/latest.log)

### Version

1.19.2

### Mod Loader Version

1.19.2 43.2.14

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
delete the tempad config and restart your game

**Comment by CodexAdrian** [comment]
This should be fixed entirely on 1.20, and the fix i mentioned seems to have worked

**Comment by ieris19** [comment]
Any idea what causes such issues? It was running fine until I updated some mods, now it doesn't want to work, even after the suggested fix.

I doubt Tempad is at fault, but knowing why this happened in the first place might help me find whatever's wrong in my specific case faster. #50 mentions mixin issues with another mod, but I'm unsure how to track that down.

Sorry that I bring the issue up again, but even if its an interaction, my only clue right now is the mod that's throwing the exception

**Comment by CosmosFury13** [comment]
im about 99% sure the error is just thrown when any other mod fails but it just comes up with tempad

**Comment by Twisted-Code** [comment]
Yeah my friends also started having this problem when we added mods. In our case one of the mods that seems to trigger the failure is HexTweaks (judging by that mod being marked as "error" in the crash report).
We are playing ATM 8, which is a very big pack already, so mod conflicts are not surprising, it's just irritating that we don't know the original stacktrace (which seems to be suppressed by the time the crash occurs here) and that it's happening intermittently.
[crash-2023-11-14_08.32.03-client.txt](https://github.com/terrarium-earth/Tempad/files/13430481/crash-2023-11-14_08.32.03-client.txt)
