### ISSUE TITLE
[Forge] (almost) No indicator for cooldown

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#5]
Version 1.1.0

There's no longer an indicator on the tempad that it's recharging and when clicking teleport you would think it's just not working.

**Comment by JaisDK** [comment]
I see there's a tooltip now, but it should be visible in the GUI as well so you don't click like an idiot on the teleport button

**Comment by CodexAdrian** [comment]
Makes sense, I’ll add one
