### ISSUE TITLE
[Bug]: Tempad Portal Rendering with Shaders

### ISSUE THREAD

**Issue by bcrotty** [terrarium-earth/Tempad#51]
### Bug Description

I updated the ATM8 modpack from their version 1.0.19b to 1.0.21b, and the Tempad portal stopped rendering when I have shaders turned on. It works fine with shaders turned off.

The modpack upgraded the following:

Tempad: tempad-forge-1.19.2-1.4.4 to tempad-forge-1.19.2-1.4.5
Forge: 43.2.11 to 43.2.14
Oculus: 1.2.8a to 1.6.4
Rubidium: 0.6.2a to 0.6.2b

I'm using Complementary Shaders 4.7.1, which come built into ATM8 and didn't change.

I'm happy to make issues in any other repos.

### How to Reproduce?

1. Try to use Tempad portal with shaders on ATM8 1.0.21b

### Expected Behavior

Portal renders

### Version

1.45

### Mod Loader Version

1.19.2-43.2.14

### Mod Loader

Forge

### Logs or additional context

timedoorFancy doesn't affect this.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Pufficles** [comment]
Having this same issue too. Have you tried setting timedoorFancy to false in the tempad config(found in the configs folder)?

**Comment by CodexAdrian** [comment]
Compatibility with shaders mods are virtually impossible so i will not be fixing this

**Comment by graveyardia** [comment]
ive been messing around with adding mod compats to complementary shaders for a couple days - when i was messing with the .jar, all of the timedoor's state files appear as corrupt, although other textures appear fine when opened. obviously will do some digging, but im wondering if that's part of the issue.
