### ISSUE TITLE
[Feature Request]: Shaders is not feasible!?

### ISSUE THREAD

**Issue by bypgomes** [terrarium-earth/Tempad#59]
### Is your feature request related to a problem?

I understand that compatibility with shaders is not feasible, so I have a suggestion that may be practical, a configuration option that can, instead of opening the portal, just teleport the player to the coordinates.

### Mod Version

1.4.4

### Mod Loader Version

43.2.14

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
No
