### ISSUE TITLE
[Forge] Configs should be in serverconfig

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#6]
Version 1.1.0

I think the new configs should be in the world/serverconfigs instead of the configs folder as this is something you'll want to control from the server side only.

**Comment by CodexAdrian** [comment]
Yeah that’s my bad, you’re completely right

**Comment by CodexAdrian** [comment]
Well the timer is checked server side now, I dont think anything more than that is required tbh.
