### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Efimity** [terrarium-earth/Tempad#61]
### Bug Description

With fwaystones mod the tempad can teleport to undiscovered/private waystones which causes a concern for privacy in the environment we use it in.

### How to Reproduce?

Open the tempad after another person other than you places a waystone and discovers it.

### Expected Behavior

You shouldn't be able to see the undiscovered waystone if it is not public.

### Version

2.1.1

### Mod Loader Version

1.20.1 - 0.14.21

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is fixed in dev, will publish soon
