### ISSUE TITLE
[Feature Request]: Shaders support

### ISSUE THREAD

**Issue by Shisuiicaro** [terrarium-earth/Tempad#63]
### Is your feature request related to a problem?

The portal doesn't appear when I use shaders

### Mod Version

1.4.1

### Mod Loader Version

1.18.2 40.2.10

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
not possible

**Comment by Shisuiicaro** [comment]
I found a way to solve this, I just activated fancy doors
