### ISSUE TITLE
[Bug]: buggy with shaders 1.20

### ISSUE THREAD

**Issue by kodamant** [terrarium-earth/Tempad#65]
### Bug Description

currently using the 1.20 version of the forge port of iris, named oculus. without blur rendering the tempad portal is comepletely invisible, with blur it appears but bugs out and glitches very frequently, turning off shaders fixes the issue

### How to Reproduce?

load up any shader
use tempad
profit (or lack there of? its there you just cant see it so maybe like, profit but only from stocks or something)

### Expected Behavior

well i expected to see it

### Version

2.1.1

### Mod Loader Version

1.20.1-forge.47.2.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Cevaconce** [comment]
I had the same problem:
Try open the "tempad_client.json" in your .minecraft/config folder and change the "TimedoorFancy" from false to true.

![20231030_122504.jpg](https://github.com/terrarium-earth/Tempad/assets/139856623/4121f1c9-e5b8-4c8c-be54-274b6b9bb535)

**Comment by CodexAdrian** [comment]
Compatibility with shader mods is limited
