### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by UnstableStrafe** [terrarium-earth/Tempad#66]
### Bug Description

The mod doesn't list that it has a required dependency on Forge of Resourceful Lib, nor does it mention it on the mod page.

### How to Reproduce?

1. Install mod
2. Resourceful Lib is not mentioned as a required dependency until you launch the game and get an error message.

### Expected Behavior

Resourceful Lib being mentioned as a required dependency

### Version

2.1.1

### Mod Loader Version

1.20.1-47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Dependencies are always correctly listed on Modrinth, which is our platform of choice. Ill include rlib in the fabric mod json / mods.toml but I recommend checking out Modrinth to view dependencies on a given version as Curseforge has decided this feature is not relevant for some reason
