### ISSUE TITLE
[Bug]: Door doesn't show with shaders enabled

### ISSUE THREAD

**Issue by JMackey1** [terrarium-earth/Tempad#67]
### Bug Description

Door will not render when shaders are enabled in Minecraft 1.20.1, Fabric 0.14.24, Iris 1.6.4, Sodium 0.4.10, Tempad 2.1.1. Doesn't matter what shader. Renders fine with shaders turned off, and the functionality is fine with shaders on (I just walk forward and teleport even if I can't see the door).

### How to Reproduce?

1. Install mods listed in description
2. Enable shaders
3. Use tempad
4. Observe door doesn't render
5. Disable shaders
6. Use tempad
7. Observe door renders

### Expected Behavior

Door should render when shaders are enabled.

### Version

2.1.1

### Mod Loader Version

0.14.24

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by PickyPixelStudio** [comment]
Same here, with Forge, and Occulus.

**Comment by CodexAdrian** [comment]
Compatibility with shader mods are not supported

**Comment by KazuKaizen** [comment]
https://www.curseforge.com/minecraft/mc-mods/tempad-with-shaders your welcome

**Comment by UberMcTuber** [comment]
i love you
