### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PickyPixelStudio** [terrarium-earth/Tempad#68]
### Bug Description

Hey,

I don't really think it's bug, probably us being dumb (not a suprise... to be honest).
But, none of us can successfully change the config file, to always tempad use experience instead of time.

```java
{
    /*
     * The distance from the player that the Tempad is summoned.
     * Range: 1 - 10
     */
    "distanceFromPlayer": 3,
    /*
     * The amount of time in ticks that the timedoor will wait before closing itself after the owner walked through it.
     * Type: Integer
     */
    "timedoorWaitTime": 100,
    /*
     * The amount of time in ticks that the Tempad will add to the wait time when the player is in the Tempad.
     * Type: Integer
     */
    "timedoorAddWaitTime": 40,
    /*
     * The amount of fuel that the timedoor will consume on opening of the timedoor.
     * Type: Integer
     */
    "timedoorFuelAmount": 180,
    /*
     * The amount of fuel that the timedoor can hold.
     * Type: Integer
     */
    "timedoorFuelCapacity": 1000,
    /*
     * The amount of fuel that the advanced timedoor will consume on opening of the timedoor.
     * Type: Integer
     */
    "advancedTimedoorFuelAmount": 1,
    /*
     * The amount of fuel that the advanced timedoor can hold.
     * Type: Integer
     */
    "advancedTimedoorFuelCapacity": 1000,
    // The type of fuel that the timedoor will consume.
    "timedoorFuelType": "tempad:timer",                                         // << THIS LINE
    // The type of fuel that the advanced timedoor will consume.
    "advancedTimedoorFuelType": "tempad:unlimited"                              // << THIS LINE
}
```

We change `tempad:timer` by `tempad:exp_points`. Change nothing in game.

The wiki must no longer be up to date.

### Version

2.1.1

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Yes the wiki only applies to 1.19 and earlier. Ill correct it this weekend

**Comment by CodexAdrian** [comment]
This is a documentation issue not a mod issue, and new docs are being deployed soon so ill close this
