### ISSUE TITLE
[Bug]: Dependencies on Modrinth

### ISSUE THREAD

**Issue by vanja-san** [terrarium-earth/Tempad#69]
### Bug Description

There are no dependencies listed on the modrinth website

### How to Reproduce?

-

### Expected Behavior

-

### Version

Latest

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Logs or additional context

![Снимок экрана 2023-11-12 180800](https://github.com/terrarium-earth/Tempad/assets/7201687/a65dab86-14d9-4ee2-887f-e82085ef44e3)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Newly published versions will contain the correct dependencies now, sorry about that
