### ISSUE TITLE
[Feature Request/Wiki]: Probably add the difference between this 'he who remains' tempad

### ISSUE THREAD

**Issue by Kiwifuit** [terrarium-earth/Tempad#70]
### Is your feature request related to a problem?

I dont know what a *'he who remains' tempad* is since i dont watch loki

### Solution(s)

Please add the difference between a normal tempad and a *'he who remains' tempad*

### Mod Version

1.4.5

### Mod Loader Version

1.19.2-43.3.0

### Mod Loader

Forge

### Additional context

Not really a bug but i just want to put an issue here

**Comment by CodexAdrian** [comment]
The difference is not always the same, the difference is defined in config and can be seen on the tooltip; the normal tempad has a cooldown, the he who remains tempad does not. this is the default behavior and can be changed
