### ISSUE TITLE
[Bug]: Latest Version Of Tempad (2.2.0) Errors upon loading on 1.20.1

### ISSUE THREAD

**Issue by Cyranos** [terrarium-earth/Tempad#71]
### Bug Description

Installing the new update causes forge to report an error when loading mods, both on my dedicated server & client.

### How to Reproduce?

Install latest update

### Expected Behavior

The game to load

### Version

2.2.0

### Mod Loader Version

47.2.6

### Mod Loader

Forge

### Logs or additional context

Server crash log; [here](https://mclo.gs/E8qFDVw)
Client crash log; [here](https://mclo.gs/1d7oDe5)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Fixed in latest, releasing soon. Sorry about that!

**Comment by Cyranos** [comment]
Ty!
