### ISSUE TITLE
[Feature Request]: Search Function or/and Location Order

### ISSUE THREAD

**Issue by Thunder-Nova** [terrarium-earth/Tempad#72]
### Is your feature request related to a problem?

When having a lot of locations on the tempad, we get a whole list of places. Yet, doesn't look like to be in a particular order.

![image](https://github.com/terrarium-earth/Tempad/assets/31967337/ed9b9393-23f6-4ee9-a811-d90ba83cc771)

So had to add Symbols such as --- to find certain places more easier

![image](https://github.com/terrarium-earth/Tempad/assets/31967337/8cece3d8-4958-4991-9f73-9091af680a81)

### Solution(s)

In Options having a "sort by":
- [Name A-Z]
- [Name Z-A]
(later on could add more, such as location from 0x 0z per dimension)

Or/And In Run Program, simply adding a search bar will do. Searching by name.

### Mod Version

2.1.1

### Mod Loader Version

1.20.1 - 47.2.14

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
Update your version of Tempad, a search function was added in 2.2.0

**Comment by Thunder-Nova** [comment]
Ah I see, lol. My bad, didn't check if there are more updated version since I didn't see the update Action icon.

Yet, I might need to check with ATM9. Might be due to Forge or Curseforge.

![image](https://github.com/terrarium-earth/Tempad/assets/31967337/0f058ed0-2945-4351-8276-147de1111ca6)
