### ISSUE TITLE
[Bug]: Render overlay error when booting up the game

### ISSUE THREAD

**Issue by R0b0r0b** [terrarium-earth/Tempad#73]
### Bug Description

When I try to load up the game, it crashes on startup, consistently, stating that there was a render overlay error. The admin of the server I play on with this modpack said that the client config is null, and that it appears that blurs are trying to load in before the config.

The crash-log mentions Xaero's Worldmap, and I know that another two mods in the pack (Hextweaks and Mediaworks) have caused a similar issue before; however, I have tried removing these mods and still suffered the same problem.

I am using the latest version for 1.19.2, as the modpack itself is on 1.19.2. Additionally, I do not believe this issue to be in the issue tracker, as similar issues have been closed, and those issues involved an update to the mod itself, while I require a solution that allows me to continue playing this specific mod-pack.

Here is the latest crash log:
https://mclo.gs/LFa9Vgf

### Version

1.4.5

### Mod Loader Version

1.19.2 - 43.3.5

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [x] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Can you try this? im not able to reproduce the issue you have so this may or may not work
[Forge](http://images.teamresourceful.com/u/gfQXds.jar)
[Fabric](http://images.teamresourceful.com/u/TklPo7.jar)

**Comment by R0b0r0b** [comment]
> Can you try this? im not able to reproduce the issue you have so this may or may not work [Forge](http://images.teamresourceful.com/u/gfQXds.jar) [Fabric](http://images.teamresourceful.com/u/TklPo7.jar)

The links don't seem to work for me

**Comment by CodexAdrian** [comment]
Forge
https://images.teamresourceful.com/u/gfQXds.jar
Fabric
https://images.teamresourceful.com/u/TklPo7.jar

**Comment by R0b0r0b** [comment]
> Forge https://images.teamresourceful.com/u/gfQXds.jar Fabric https://images.teamresourceful.com/u/TklPo7.jar

So, I eventually managed to fix the problem - it turns out I somehow managed to download a 1.16.5 version of a clientside mod. I replaced it, and now the game's working. Thank you for all the help, though!
