### ISSUE TITLE
[Feature Request]: Shader compatibility

### ISSUE THREAD

**Issue by MikeHollisJr2021** [terrarium-earth/Tempad#76]
### Is your feature request related to a problem?

Yes, becasue it will keep causing issues to appear until it's implimented, 

### Solution(s)

I would like the Tempad door to appear and operate as normal when shaders are enabled.

### Describe alternatives you've considered

1) Alternative shaders, 
2) Turning shaders off, using the tempad, turning shaders back on
3) Not using Tempad

### Mod Version

2.2.4

### Mod Loader Version

1.20.1 - Forge 47.2.16

### Mod Loader

Forge

### Additional context

This is a great mod, and it really deserves to shine in a great looking environment.

**Comment by CodexAdrian** [comment]
I answered this question already, the answer is no, theres just no way to do it
