### ISSUE TITLE
[Feature Request]: add option to change the colour back

### ISSUE THREAD

**Issue by simfrek** [terrarium-earth/Tempad#79]
### Is your feature request related to a problem?

The option to change colour is no longer available since the new updated ui screen, anyone on the server that already changed their colours has remained that colour since the update but nobody can change their colour

### Solution(s)

could you please add a small button someone to allow to change colours or possibly add a crafting option to dye the tempad to change the colour

### Mod Version

2.30

### Mod Loader Version

47.2.16

### Mod Loader

Forge

### Additional context

I am currently playing ATM 9 version 0.2.32 so you are able to see other mods in the pack incase of any conflicts

**Comment by CodexAdrian** [comment]
No

**Comment by CodexAdrian** [comment]
The tempad has alot more flexibility now, you can change the entire UI if you wanted to, including changing the color of the on screen elements, and you can still use the client config to change the color of the text and the portals. I have no intention of bringing back the old, rudimentary and very limited system

**Comment by simfrek** [comment]
![image](https://github.com/terrarium-earth/Tempad/assets/3540773/4601d5f3-8f29-4ae0-a298-46dbfda42752)

i'm sorry I dont see this as an option anywhere how would I go about changing the UI?

**Comment by CodexAdrian** [comment]
You can change the UI now in the way you would change any other UI, via a resourcepack. Doing it this way gives you even more flexibility than the old system, which would only allow you to change what a single grid square looked like
