### ISSUE TITLE
[Forge] Odd location name sorting

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#8]
Version 1.1.0

The second "roof" was added last, so the list is not sorted alphabetically nor by latest.

![image](https://user-images.githubusercontent.com/15868585/158420846-abecc3fd-5bde-4257-b681-37e0826c28b3.png)

**Comment by CodexAdrian** [comment]
I don’t do any sorting, I assume it’s just sorting by the locations random UUID. I’ll make it sort in a more intuitive way

**Comment by CodexAdrian** [comment]
Fixed
