### ISSUE TITLE
[Bug]: Can't change config

### ISSUE THREAD

**Issue by Borailuce99** [terrarium-earth/Tempad#80]
### Bug Description

I'm currently using Tempad 2.3.1 on my client and my server but when I try to change the config file to use "exp_levels" instead of "timer", nothing changes. I also edit the amount of fuel consumed and it changes from 180s to 30s correctly but, as said, if I change "timedoorFuelType": from "tempad:timer" to "tempad:exp_levels", it doesn't work.
I have seen there was an issue talking about it and finished saying that it was a wiki problem that is outdated to 1.19 but, what wiki are you talking about? the curseforge page of the mod? I also have seen that there should be an option to change colour of the portals but I can't figure out where is this option.

### Version

2.3.1

### Mod Loader Version

1.20.1 Fabric 0.15.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is because the wiki is out of date. Ill look into publishing a new wiki soon

**Comment by CodexAdrian** [comment]
Documentation is now live at https://tempad.wiki/tempad.html
