### ISSUE TITLE
[Feature Request]:  Ability ro remove timedoors.

### ISSUE THREAD

**Issue by UnderseaKnight** [terrarium-earth/Tempad#81]
### Is your feature request related to a problem?

Whenever I open a timedoor, it just stays there and wont ever despawn

### Solution(s)

Either have it disappear automatically or after every player in the vicinity enters it. either that or add a close timedoor function to the tempad

### Mod Version

2.3.1

### Mod Loader Version

1.20

### Mod Loader

Forge

**Comment by CodexAdrian** [comment]
That shouldnt be possible, timedoor entities will automatically discard themselves after a certain amount of time and are not saved to the chunk, leaving and coming back should make the portal disappear. If this is the case im gonna need some more information to try and replicate this issue

**Comment by CodexAdrian** [comment]
Have you changed some of the config values?

**Comment by UnderseaKnight** [comment]
Everything is fine now. I think it was bugged or something for a bit, my server's pretty slow. After a restart, it disappeared, and now they are disappearing after a bit by themselves, so don't worry about it.

**Comment by CodexAdrian** [comment]
Awesome
