### ISSUE TITLE
[Bug]: /feature needed - shaders support / Portal entity invisibility

### ISSUE THREAD

**Issue by SomRandom-Guy** [terrarium-earth/Tempad#83]
### Bug Description

the mod is great, the recharge time may be long, but its nice.
The mod has some kind of issue when dealing whit shaders, where the portal entity becomes invisible, the version of shaders i am using are Complementary shaders - reimagined /  Complementary shaders - unbound.

### How to Reproduce?

1. download the tempad mod 2. install complementary shaders 3. enter the game with shaders active and try to use the tempad 4. even though it is usable, portal entity is invisible

### Expected Behavior

i would like a fix for the issue, the mod is nice and would love to use it more

### Version

1.4.0

### Mod Loader Version

tempad-forge-1.20.1-2.3.3.jar

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This issue is not solvable, apologies

Also you can configure the cooldown for the tempad. Wiki explains how: https://tempad.wiki

**Comment by SomRandom-Guy** [comment]
also, how does one get the he who remains version of the tempad?

**Comment by CodexAdrian** [comment]
> also, how does one get the he who remains version of the tempad?

Its a rare find in end city dungeon loot

**Comment by SomRandom-Guy** [comment]
thanks for all
