### ISSUE TITLE
[Bug]: portal display

### ISSUE THREAD

**Issue by grante36** [terrarium-earth/Tempad#84]
### Bug Description

Hi, I'm using your great "Tempad" mod with a "Complementary" shader on a modpack and when activating the teleportation portal I don't see it, is there a particular configuration to do or something else

### How to Reproduce?

Ragnamod 7 modpack and ComplementaryUnbound_r 5.1.1 shaders pack and oculus mod for use a shaders

### Expected Behavior

the display of the portal when it is activated

### Version

1.4.1

### Mod Loader Version

1.18.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by MKr4zy** [comment]
Same Problem here, Modpack ATM9, ComplementaryReimagined_r5.1.1, MC Version 1.20.1.
As soon, as I disable the shaders, the portal is visible again.

**Comment by CodexAdrian** [comment]
this is a known issue, Tempad is not compatible with shaders
