### ISSUE TITLE
[Feature Request]: Emulate /tpa command to teleport to friends

### ISSUE THREAD

**Issue by TheDeviantCrafter** [terrarium-earth/Tempad#85]
### Is your feature request related to a problem?

FTB Essentials adds a /tpa command which lets you teleport to another player with their permission. This is very useful for servers... but using commands isn't immersive and doesn't look as cool.

### Solution(s)

My proposal is to add a way to link two Tempads together.

1. Crafting two Tempads together in a crafting table links them together (the other tempad stays in the crafting table like buckets when crafting cake)
2. Both tempads now have the other Tempad as a waypoint
3. If another player is online with a linked Tempad in their inventory, your Tempad's waypoint will be renamed to that player's username
4. Teleporting to that waypoint creates a portal to the first safe block in a 5x5x5 area around the target player
5. Deleting the waypoint unlinks both Tempads, preventing the other player from teleporting to you as well
6. Alternatively the waypoint can be locked if you want temporary privacy

### Describe alternatives you've considered

The /tpa command

### Mod Version

2.3.3

### Mod Loader Version

1.20.1 - 47.2.19

### Mod Loader

Forge

**Comment by TheDeviantCrafter** [comment]
If this is added, would it be possible to automatically add your FTB Teams members to your linked Tempad list?

**Comment by CodexAdrian** [comment]
This is interesting. let me think about how to go about this. Also id likely add support for Argonauts, idk about FTB Teams

**Comment by TheDeviantCrafter** [comment]
Another option is to add a friend card that can be created with a button in the UI. This might be easier to discover than a crafting recipe.
