### ISSUE TITLE
[Feature Request]: Global waypoints similar to Waystones

### ISSUE THREAD

**Issue by TheDeviantCrafter** [terrarium-earth/Tempad#86]
### Is your feature request related to a problem?

Waystones allows players in creative mode to create global waypoints. These will appear for all players even if they have never traveled there before. I would like to use Tempad in place of Waystones for my modpack but this feature is holding me back.

### Solution(s)

When creating a waypoint, there is a checkbox with a globe icon. Checking it sets the waypoint as a global waypoint meaning it applies to everyone's Tempads.

By default this can only be done in creative mode, but a config would allow all players to make global waypoints.

### Describe alternatives you've considered

Sticking with Waystones for global waypoints, or expecting players to share location cards.

### Mod Version

2.3.3

### Mod Loader Version

1.20.1 - 47.2.19

### Mod Loader

Forge

**Comment by TheDeviantCrafter** [comment]
After posting this I realized that Waystones waypoints appear in the Tempad. I guess I'm keeping Waystones.

**Comment by CodexAdrian** [comment]
Done in 1.21
