### ISSUE TITLE
[Feature Request]: He who remains tempad recipe

### ISSUE THREAD

**Issue by SomRandom-Guy** [terrarium-earth/Tempad#87]
### Is your feature request related to a problem?

Hello, i have been playing in a modpack called all the mods 9, i have visited over 12-15 end cities in search of the tempad from he who remains, due to the nature of the modpack i cannot change the charge type or time of the tempad, so i've been looking for the version without charge, but to no avail, be it because of its rarity or because of overlaping in the loot table for the chests i havent been able to find it. 

### Solution(s)

I propose a addition of a end game recipe, 4 nether stars in corners, an ender eye in middle and 2 netherite blocks on top and bottom and 2 gold blocks on the sides. It would be great for cases like me and it could be a choice for the challenge to get it, being as hard as the search procedure.

### Mod Version

1.4.0

### Mod Loader Version

tempad-forge-1.20.1-2.3.3.jar

**Comment by CodexAdrian** [comment]
Request it from the modpack author, the recipe wont be added to the base mod
