### ISSUE TITLE
[Bug]: Potential to become stuck in time door

### ISSUE THREAD

**Issue by Thedude7054** [terrarium-earth/Tempad#89]
### Bug Description

An edge case exists where it is possible to become stuck in a time door "loop"

### How to Reproduce?

1. Create time door location in Tempad
2. Move the same distance as "distanceFromPlayer" in tempad.jsonc *behind* where your time door spawns. ie if your time door spawns at -71 72 3, move to -68 72 3
3. When you attempt to travel through the time door you become stuck between both the entrance and exit doors
The only way I have found to become unstuck is to run `/kill @e[type=tempad:timedoor]`, or to exit and rejoin the game if in single player.

### Expected Behavior

Suggested solution is an option in the Tempad as well as a key bind to close your summoned time doors

### Version

2.3.3

### Mod Loader Version

1.20.4 - 0.15.3

### Mod Loader

Fabric

### Logs or additional context

My tempad.jsonc file is stock save for both "timedoorWaitTime" and "timedoorAddWaitTime" being increased 20 ticks each. Additionally in tempad-client.jsonc, "renderBlur" has been set to true. The bug still occurs with default values.

![2024-01-17_04 09 53](https://github.com/terrarium-earth/Tempad/assets/11370996/2699b07e-6407-4c3b-a629-28de29c78f40)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [x] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is fixed in 1.21! Completely random side point, you opened this issue on my birthday lol
