### ISSUE TITLE
[Forge] Boats don't teleport well

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#9]
Version 1.1.0

Teleporting while in a boat is sketchy and the portal is placed too low

**Comment by CodexAdrian** [comment]
Define sketchy. I’ll test this tonight and see how I can improve placement of the portal in boats

**Comment by JaisDK** [comment]
![Uploading image.png…]()
combined with the half block bug :D

**Comment by JaisDK** [comment]
![image](https://user-images.githubusercontent.com/15868585/158426597-f24e6f1d-60cc-4a6d-9a60-1ff7023bae12.png)

**Comment by CodexAdrian** [comment]
Ah. Alright I’ll see what I fix

**Comment by CodexAdrian** [comment]
Alright well as a temporary fix, all entities that step through the Timedoor get dismounted and then teleported. This is better than vanilla that dont teleport mounted entities at all. I'll see if I can come up with a better solution.
