### ISSUE TITLE
[Feature Request]: Add config option to seperate cooldowns for Tempads

### ISSUE THREAD

**Issue by 4dTailor** [terrarium-earth/Tempad#90]
### Is your feature request related to a problem?

Currently, if you use a Tempad with a timer as it's fuel source, it'll activate the cooldown for both types of Tempad, regardless of the other's fuel source.

### Solution(s)

In the config is an option, like "seperateTempadCooldowns", which when enabled would seperate the cooldowns of both Tempads, preventing a conflict where a Tempad with a higher cooldown would disable a Tempad with a lower cooldown.

### Describe alternatives you've considered

N/A

### Mod Version

2.3.3

### Mod Loader Version

1.20.1 - 0.15.5

### Mod Loader

Fabric

### Additional context

My intention was to have the basic Tempad run on energy, while the advanced Tempad uses a cooldown, giving a reason to use the advanced Tempad, without rendering the basic Tempad redundant.

**Comment by CodexAdrian** [comment]
fixed in 1.21
