### ISSUE TITLE
[Bug]: i cant open the crafting grid 

### ISSUE THREAD

**Issue by DaimDud3** [terrarium-earth/Tempad#94]
### Bug Description

i cant open the crafting grid using the philosophers stone. i tried everything and it doesnt work. i dont know if im doing it wrong or if its an actual bug

### Version

the latest

### Mod Loader Version

1.19.2

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
The... philosphers stone...? You know this is Tempad and not ProjectE right?

**Comment by CodexAdrian** [comment]
Yeah never seems we got an answer to this one lol
