### ISSUE TITLE
[Feature Request]: Add an option to balcklist entities

### ISSUE THREAD

**Issue by AHL67** [terrarium-earth/Tempad#95]
### Is your feature request related to a problem?

Some entities should not be teleported by the tempad, like end crystals, falling blocks, fishing bobbers, markers, possibly projectiles, or even more problematic, Create contraptions. We really need a way to blacklist such entities to avoid serious issues.

### Solution(s)

The best way to set an entity blacklist would be to use an entity tag, something like `#tempad:blacklist`, that you can fill with entities not allowed to interact with the tempad portal. This solution would allow other mods or modpack makers to add their own entities with ease.

### Describe alternatives you've considered

Another solution would be to set the blacklist in a config file, but it would be way less flexible.

### Mod Version

1.4.1

### Mod Loader Version

1.18.2 - 40.2.17

### Mod Loader

Forge

### Additional context

Entities that shoul be blacklisted by default include (but are not limited to):
```
minecraft:end_crystal‌
minecraft:evoker_fangs‌
minecraft:falling_block
minecraft:fishing_bobber‌
minecraft:glow_item_frame
minecraft:interaction
minecraft:item_display
minecraft:item_frame
minecraft:lightning_bolt
minecraft:leash_knot
minecraft:marker
minecraft:painting
minecraft:text_display
create:carriage_contraption
create:contraption
create:crafting_blueprint
create:gantry_contraption
create:seat
create:stationary_contraption
create:super_glue
```

Also, I make the request for Minecraft 1.18.2 in the hope of getting an update to include in the modpack Ragnamod VII, but the request is of course valid for all versions.

**Comment by CodexAdrian** [comment]
1.18 is no longer supported. This has already been implemented in later versions
