### ISSUE TITLE
[Feature Request]: Folders/Categories for better location management

### ISSUE THREAD

**Issue by OarisHunter** [terrarium-earth/Tempad#98]
### Is your feature request related to a problem?

Overtime, finding the location in the small menu gets unruly

### Solution(s)

A collapsible folder structure would work well, ideally allowing the "root" folder to contain locations and additional folders, even if folders couldn't be nested.

### Describe alternatives you've considered

If a predefined structure would be simpler, preset categories would be nice. 

### Mod Version

2.3.3

### Mod Loader Version

1.20.1 - 0.15.6

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
Implemented in 1.21
