### ISSUE TITLE
[Feature Request]: "Lore accurate" Tempad mode (AKA: overpowered tempad settings)

### ISSUE THREAD

**Issue by KateReller** [terrarium-earth/Tempad#99]
### Is your feature request related to a problem?

Not necessarily a problem, but when I saw this mod I thought it was something to let me teleport to anywhere from anywhere (a glorified /tp command pretty much). But it only TPs to predefined spots where you have had to been at.

### Solution(s)

There should be maybe two settings:
1. Set both tempad types to be overpowered versions and allow teleporting to any coords to any dimension. 
2. Set only the "He Who Remains" variant of the tempad to be the overpowered one. 

### Mod Version

2.3.3

### Mod Loader Version

1.20.1-47.2.0

### Mod Loader

Forge

### Additional context

This will probably require checks for if where you're teleporting to is valid and isn't obstructed by blocks within a certain area.

**Comment by CodexAdrian** [comment]
I dont plan to add this to the base mod, but 1.21 introduces an API for developing new features to the tempad item that makes this easy to implement. An addon for Tempad adding will be something I'd be willing to develop
